// Generated by dts-bundle v0.4.3

declare module 'apitest' {
    import { helloWorld } from 'apitest/lib/helloworld';
    export { helloWorld };
}

declare module 'apitest/lib/helloworld' {
    let helloWorld: string;
    export { helloWorld };
}

