// Generated by dts-bundle v0.4.3
// Dependencies for this module:
//   express

declare module 'apitest' {
    import { helloWorld } from 'apitest/lib/helloworld';
    export { helloWorld };
    import { app } from 'apitest/lib/server';
    export { app };
}

declare module 'apitest/lib/helloworld' {
    let helloWorld: string;
    export { helloWorld };
}

declare module 'apitest/lib/server' {
    import * as express from 'express';
    let app: express.Application;
    export { app };
}

